# Generated by Django 5.2.1 on 2025-05-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mask', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('eq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipmenttype')),
            ],
            options={
                'unique_together': {('eq_type', 'serial_number')},
            },
        ),
    ]
