# Generated by Django 5.2.1 on 2025-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
