# Generated by Django 5.2.1 on 2025-05-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_equipment_serial_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
