# Generated by Django 5.2.1 on 2025-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_equipment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
