# Generated by Django 5.2.1 on 2025-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_equipment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
